"""
script_generator.py - ジャンル別台本・メタデータ生成モジュール

- 動画尺: 40秒（~200文字 / ナレーション読み上げ速度300文字/分）
- シーン: 1〜2個・合計40秒
- ハッシュタグ: トレンドデータから動的生成・ちょうど5個
- 説明文: 冒頭に「#PR」・末尾にアフィリ誘導文を自動挿入
- prompt_hintsシートの改善ヒントをプロンプトに反映

使用モデル: Gemini 2.5 Flash
環境変数: GEMINI_API_KEY
"""

import os
import json
import logging
from google import genai
from spreadsheet import SpreadsheetManager

logger = logging.getLogger(__name__)

MODEL_NAME = "gemini-2.5-flash"

GENRE_HASHTAG_STYLE = {
    "zatugan": "拡散重視・#雑学 #豆知識 #知識 系を中心に",
    "setsuyaku": "CVR重視・#節約 #お金 #NISA #ポイ活 系を中心に",
    "lifehack": "保存重視・#ライフハック #時短 #便利 系を中心に",
}

# ジャンル別・冒頭3秒の掴みパターン
GENRE_HOOK_PATTERNS = {
    "zatugan": '「え、これ知ってた？」「実は〇〇だった」「学校で教えてくれなかった〇〇」「〇〇の闇が深すぎる」「99%の人が勘違いしてる〇〇」',
    "setsuyaku": '「正直に言います、〇〇してる人は損してます」「銀行が絶対教えない話」「まだ〇〇してるの？」「知ってる人だけが得してる」「月〇万捨ててるのと同じです」',
    "lifehack": '「これ神すぎる」「〇〇はもうやめて」「〇〇使ってる人もったいなすぎる」「え、こんな使い方できるの？」「これ知らないの情弱です、優しく言うと」',
}


def generate_script(
    genre: str,
    theme: str,
    product_name: str = "",
    affiliate_url: str = "",
    pr_points: str = "",
    trend_data: dict = None,
    prompt_hints: dict = None,
) -> dict:
    """
    テーマ・商品名・トレンドデータから台本・タイトル・説明文・シーン情報をJSON形式で生成する。

    Args:
        genre: 'zatugan' | 'setsuyaku' | 'lifehack'
        theme: 動画テーマ
        product_name: 紹介商品名（アフィリエイト）
        affiliate_url: アフィリエイトURL（説明文に直接挿入）
        pr_points: 広告主PRポイント（Geminiの紹介文生成に活用）
        trend_data: spreadsheetから取得した最新トレンドデータ（Noneの場合は参照なし）
        prompt_hints: prompt_hintsシートから取得した改善ヒント（Noneの場合は参照なし）

    Returns:
        {
          "script": str,
          "title": str,
          "description": str,
          "hashtags": [str, ...],  # ちょうど5個
          "scenes": [{"keyword": str, "duration": int}, ...]
        }
    """
    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

    trend_section = _build_trend_section(trend_data)
    hint_section = _build_hint_section(prompt_hints)
    affili_section = _build_affili_section(product_name, affiliate_url, pr_points)
    hashtag_style = GENRE_HASHTAG_STYLE.get(genre, "")
    hook_patterns = GENRE_HOOK_PATTERNS.get(genre, "")

    prompt = f"""テーマ「{theme}」についてSNSショート動画（40秒）用コンテンツを生成してください。
以下のJSON形式のみで出力してください（JSONの外にテキストを書かないこと）。

{{
  "script": "ナレーション台本（200文字程度の日本語。下記【構成の型】に従い、話し言葉・断言口調で書く）",
  "title": "タイトル（20文字以内・数字や疑問形・「知らなかった」「実は〇〇」「やばすぎる」などの型を使う・末尾に「 #Shorts」を必ず付ける）",
  "description": "説明文（最初の1〜2行にキーワードを含め内容の概要を100文字程度で記述。#PRは冒頭に自動挿入するため不要）",
  "hashtags": ["#ハッシュタグ1", "#ハッシュタグ2", "#ハッシュタグ3", "#ハッシュタグ4", "#ハッシュタグ5"],
  "scenes": [
    {{"keyword": "背景動画の英語検索キーワード（具体的かつ映像的に）", "duration": シーンの秒数（整数）}},
    {{"keyword": "...", "duration": ...}}
  ]
}}

【冒頭3秒の掴みパターン（このジャンルで使うこと）】
{hook_patterns}
→ 掴みは必ず「否定・暴露・数字・煽り」のどれかで始める。
→ 最初の一文で視聴者が「これ自分のことだ」「続きを見ないとやばい」と思わせること。
→ 特に「否定から入る」「視聴者を主語にする」パターンを積極的に使うこと。

【構成の型（scriptはこの順番で書くこと）】
① 掴み（〜3秒）  ：否定・暴露・数字で強く引き付ける（例：「正直に言います」「まだ〇〇してるの？」）
② 自分ごと化（〜6秒）：「あなたも絶対やってると思うんですけど」「これ、損してる人の典型パターンで」
③ 不安を上げる（〜10秒）：「このまま続けると〇〇になります」「知らないと5年後に後悔します」
④ 解決策・情報（〜33秒）：具体的な数字・手順・事実で展開。「知ってる人だけが得してる」視点で
⑤ アフィリ誘導（〜38秒）：商品を視聴者メリットとして自然に紹介
⑥ 行動喚起（〜40秒）：「今すぐプロフのリンクをチェック」等の短い一言

【完走率を上げる仕掛け（必ず2つ以上使うこと）】
- 数字で煽る：「9割の人が損してる」「月3万捨ててるのと同じ」「10秒でできる」
- 対比を使う：「知ってる人 vs 知らない人」「やってる人だけ得してる」「情弱 vs 賢い人」
- 不安を煽ってから救う：「このままだと〇〇になる」→「でも解決策があって」
- 余韻を残す：「実はこれ、まだ続きがあって…」「詳しくはプロフから」

【NG表現（絶対に使わないこと）】
- 「ぜひ」「いかがでしょうか」「〜してみてください」等の丁寧すぎる表現
- 「〜されています」「〜と言われています」等の受動的・他人事な表現
- 「〜が大切です」「〜を意識しましょう」等の弱い締め
- 長い説明文・回りくどい言い回し・箇条書きの羅列
- 結論を最後まで引っ張りすぎる構成（最初に結論を一言言ってから深掘りすること）
{trend_section}
{hint_section}
制約:
- scriptは自然な話し言葉・断言口調で書く（読み上げ速度: 300文字/分 → 40秒で約200文字）
- scenesは1〜2個・合計duration は40秒前後に合わせる
- keywordは英語で具体的に（例: "saving money coins jar"）
- titleは20文字以内・末尾に「 #Shorts」を必ず付ける
- titleに「#」はShortsのみ許可・絵文字は不要
- hashtagsは{hashtag_style}・テーマに合わせて動的生成・必ずちょうど5個
- descriptionにhashtagsを含めないこと（別フィールドで管理）{affili_section}"""

    REQUIRED_KEYS = ("script", "title", "description", "hashtags", "scenes")
    last_error = None

    for attempt in range(3):
        if attempt > 0:
            logger.warning(f"Retrying Gemini request (attempt {attempt + 1}/3)...")

        response = client.models.generate_content(model=MODEL_NAME, contents=prompt)
        raw_text = response.text.strip()
        logger.info("Script generated by Gemini")

        if "```json" in raw_text:
            raw_text = raw_text.split("```json")[1].split("```")[0].strip()
        elif "```" in raw_text:
            raw_text = raw_text.split("```")[1].split("```")[0].strip()

        try:
            data = json.loads(raw_text)
        except json.JSONDecodeError as e:
            logger.warning(f"JSON parse error (attempt {attempt + 1}): {e}")
            last_error = e
            continue

        missing = [k for k in REQUIRED_KEYS if k not in data]
        if missing:
            logger.warning(f"Missing keys (attempt {attempt + 1}): {missing}")
            last_error = ValueError(f"Missing key: '{missing[0]}'")
            continue

        break
    else:
        raise ValueError(f"Gemini failed after 3 attempts: {last_error}")

    # ハッシュタグが5個でない場合は調整
    hashtags = data["hashtags"]
    fallback_tags = {
        "zatugan": ["#雑学", "#豆知識", "#知識", "#面白い", "#学び"],
        "setsuyaku": ["#節約", "#お金", "#ポイ活", "#NISA", "#貯金"],
        "lifehack": ["#ライフハック", "#時短", "#便利", "#効率化", "#裏技"],
    }
    if len(hashtags) != 5:
        logger.warning(f"Hashtag count is {len(hashtags)}, adjusting to 5")
        fallback = fallback_tags.get(genre, fallback_tags["zatugan"])
        merged = list(dict.fromkeys(hashtags + fallback))  # 重複排除しつつ順序保持
        hashtags = merged[:5]
        data["hashtags"] = hashtags

    # タイトル末尾に「 #Shorts」を確実に付与
    title = data["title"]
    if not title.endswith("#Shorts"):
        title = title.rstrip() + " #Shorts"
        data["title"] = title

    # 説明文の先頭に「#PR」を付与・末尾にアフィリ誘導文を追加
    description = data["description"].strip()
    hashtag_str = " ".join(hashtags)
    if product_name and affiliate_url:
        # URLがある場合は直接リンクを挿入（YouTube・TikTok向け）
        affili_line = f"\n\n👆「{product_name}」はこちら\n{affiliate_url}"
    elif product_name:
        # URLがない場合はプロフ誘導（Instagram向けフォールバック）
        affili_line = f"\n\n👆プロフのリンクから「{product_name}」をチェック！"
    else:
        affili_line = ""
    data["description"] = f"#PR\n{description}{affili_line}\n\n{hashtag_str}"

    logger.info(f"Title: {data['title']}")
    logger.info(f"Hashtags: {data['hashtags']}")
    logger.info(f"Scene count: {len(data['scenes'])}")
    return data


def _build_trend_section(trend_data: dict | None) -> str:
    """トレンドデータをプロンプト用テキストに変換する"""
    if not trend_data:
        return ""

    lines = ["\n【最新トレンドデータ（参考にして生成すること）】"]

    if trend_data.get("title_patterns"):
        patterns = trend_data["title_patterns"]
        if isinstance(patterns, list):
            lines.append(f"- バズるタイトルの型: {', '.join(patterns)}")
        else:
            lines.append(f"- バズるタイトルの型: {patterns}")

    if trend_data.get("hook_style"):
        lines.append(f"- 効果的な掴み方: {trend_data['hook_style']}")

    if trend_data.get("recommended_hashtags"):
        hashtags = trend_data["recommended_hashtags"]
        if isinstance(hashtags, list):
            lines.append(f"- 推奨ハッシュタグ（優先的に使用）: {' '.join(hashtags)}")

    lines.append("")
    return "\n".join(lines)


def _build_hint_section(prompt_hints: dict | None) -> str:
    """自動改善ループのscript_hintをプロンプトに組み込む"""
    if not prompt_hints or not prompt_hints.get("script_hint"):
        return ""
    return f"\n【今週の改善指示（必ず反映すること）】\n{prompt_hints['script_hint']}\n"


def _build_affili_section(product_name: str, affiliate_url: str = "", pr_points: str = "") -> str:
    """アフィリエイト商品をscriptに自然に組み込む指示を追加する"""
    if not product_name:
        return ""
    url_hint = "・説明欄のリンクから確認できることを一言添えること" if affiliate_url else ""
    pr_hint = f"\n- 紹介時に以下のPRポイントを参考にすること（そのまま読まず、動画の流れに合わせて自然に一言に凝縮する）:\n  {pr_points}" if pr_points else ""
    return (
        f"\n- scriptの最後の一文で「{product_name}」を自然に紹介すること"
        f"（押し売り感なく、視聴者のメリットとして伝える）{url_hint}"
        f"{pr_hint}"
    )


if __name__ == "__main__":
    import argparse
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    parser = argparse.ArgumentParser(description="台本自動生成")
    parser.add_argument("--genre", required=True, choices=["zatugan", "setsuyaku", "lifehack"])
    parser.add_argument("--theme", required=True)
    parser.add_argument("--product", default="", help="紹介商品名")
    parser.add_argument("--url", default="", help="アフィリエイトURL")
    parser.add_argument("--pr", default="", help="広告主PRポイント")
    args = parser.parse_args()

    sheet = SpreadsheetManager(args.genre)
    trend = sheet.get_latest_trend()
    hints = sheet.get_prompt_hints()

    result = generate_script(args.genre, args.theme, args.product, args.url, args.pr, trend, hints)
    print(json.dumps(result, ensure_ascii=False, indent=2))
